### ISSUE TITLE
황보은준 OPG 가입신청서

### ISSUE THREAD

**Issue by Jun-77** [Openmind-Programming-Group/Introduction#2]
### 신청 계기 ❓

- 과 선배님이 카톡방에 홍보해 주셔서 OPG를 알게 되었고, 제가 코딩에 대해 초보인 만큼 더 열심히 공부하고 싶어 지원했습니다.

### 기대되는 활동 또는 원하는 활동 📌

- 밤샘코딩과 작품전시회가 가장 기대됩니다.

### 앞으로의 기대 ❗️

- 밤샘코딩도 하고, 저만의 작품을 만들려고 하면서 저의 코딩, 알고리즘 설계 능력 등을 키워나갈 것입니다.

**Comment by WhiteHyun** [comment]
환영합니다 :) 가입 완료되셨습니다 😁
