### ISSUE TITLE
OPG 가입신청

### ISSUE THREAD

**Issue by seoyeon02** [Openmind-Programming-Group/Introduction#3]
### 신청 계기 ❓

- **컴퓨터공학부 공지방에 올라온 글을 보고 알게 되었습니다**

### 기대되는 활동 또는 원하는 활동 📌

- **OPG의 모든 활동이 기대되지만 세미나와 스터디가 특히 기대됩니다! 추가로 공모전 참가를 함께 하는 것도 좋을 것 같아요!**

### 앞으로의 기대 ❗️

- **OPG의 다양한 활동에 적극적으로 참여하고 선배님들이 알려주시는 것들 열심히 배워서 실질적인 실력을 키워나가겠습니다. 감사합니다!!**

**Comment by WhiteHyun** [comment]
가입 완료! 만나서 반갑습니다 :)
