### ISSUE TITLE
OPG 면압

### ISSUE THREAD

**Issue by dhcorjs** [Openmind-Programming-Group/Introduction#4]
### 신청 계기 ❓

- **OPG는 학과톡방에서 홍보하시는 것을 보고 알게되었습니다. 고등학교 때 C언어를 간단히 배우는 시간이 있었는데 C언어를 배워서 혼자 작성하는 것보다도 간단한 프로그램이라도 여럿이서 아이디어를 제출해서 신박한 방식으로 코드를 구현하는 것이 더 재밌다고 생각했습니다. 그래서 3~4명의 팀별 형식인 OPG에서 모르는 부분도 배우면서 재밌게 코딩 공부를 하고 싶어서 지원하게 되었습니다.**

### 전공 경험 🔍

  

- **C와 C++을 살짝 배웠습니다. 그래도 처음하는 마인드로 공부하고 싶습니다.**

### 기대되는 활동 또는 원하는 활동 📌

- **고등학교 때는 시간에 제약이 있었지만 대학와서는 밤샘코딩을 해보고 싶다는 생각을 했고 다른 사람들과 토론하고 발표도 하는 그런 세미나 활동도 기대됩니다!!**

### 앞으로의 기대 ❗️

- **앞으로의 프로그램에 있어서 기존의 코드와 다르게 점점 복잡해질 것이기 때문에 코드를 짜는 부분에 있어서 협력해서 아이디어를 합치는 법을 배우고 싶습니다. 그리고 나중에 코딩이 들어간 제품에 사람들의 불만이 생겼을 때 그것을 해결하기 위해 새로운 알고리즘을 짜고 그 알고리즘을 구현화할 수 있는 코딩 실력을 기르기 위해 공부하고 싶습니다.**

**Comment by WhiteHyun** [comment]
가입완료! 환영합니다 :)
