### ISSUE TITLE
이제빈 OPG 가입신청

### ISSUE THREAD

**Issue by leejebeen** [Openmind-Programming-Group/Introduction#5]
### 신청 계기 ❓

- 컴퓨터공학부 단톡방을 통해 알게되었습니다.

### 전공 경험 🔍

  

- 전공 관련지식은 거의 없습니다.

### 기대되는 활동 또는 원하는 활동 📌

- 밤샘코딩이 가장 기대됩니다.

### 앞으로의 기대 ❗️

- 코딩 관련지식이 거의 없기 때문에 열심히 코딩을 배워서 관련 지식을 늘려가고 싶습니다.

**Comment by WhiteHyun** [comment]
만나서 반갑습니다 😁 카카오톡 문자 하나 남겨주시면 감사하겠습니다!
제 카카오톡 ID는 `whitehyun2513` 입니다.
