### ISSUE TITLE
21학번 김경진 OPG 신청서

### ISSUE THREAD

**Issue by kimkyeong9719** [Openmind-Programming-Group/Introduction#6]
### 신청 계기 ❓

- **선배님이 알려주셔서 알게 되었고, 선배님과 멘토링 활동을 하는것과 밤샘코딩에 흥미가 있어서 지원했습니다.**

### 전공 경험 🔍

  

- **없습니다.**

### 기대되는 활동 또는 원하는 활동 📌

- **21학번 친구들과 같이 프로젝트 짜서 밤샘코딩 해보고 싶습니다.**

### 앞으로의 기대 ❗️

- **머릿속이 백지 상태라 더욱 선배님들의 조언을 잘 흡수하고 적용할 수 있을것같습니다. 여유시간이 많아졌다고 놀지않고 전공공부를 꾸준히 해서 예비22학번후배들을 이끌어갈 수 있도록 노력하겠습니다**

**Comment by WhiteHyun** [comment]
- 훌륭한 마음가짐입니다!

  > _머릿속이 백지 상태라 더욱 선배님들의 조언을 잘 흡수하고 적용할 수 있을것같습니다. 여유시간이 많아졌다고 놀지않고 전공공부를 꾸준히 해서 예비22학번후배들을 이끌어갈 수 있도록 노력하겠습니다_

- 선배가 누군지 알려주실 수 있나요? 칭찬해드려야겠네요 🤣
  > _선배님이 알려주셔서 알게 되었고, 선배님과 멘토링 활동을 하는것과 밤샘코딩에 흥미가 있어서 지원했습니다._

- 마지막으로 저에게 카카오톡 문자 하나 남겨주시면 감사하겠습니다! 제 카카오톡 ID는 `whitehyun2513` 입니다.
