### ISSUE TITLE
OPG 가입신청

### ISSUE THREAD

**Issue by janghyunBBBB** [Openmind-Programming-Group/Introduction#7]
### 신청 계기 ❓

- **컴퓨터공학부 선배님이 단체톡방에 OPG동아리에 대해 소개 해 주셨습니다. 그래서 같은 전공을 하고있는 선배님들이랑 친해지고 같이 공부도 하고 싶기 때문에 지원을 하게 되었습니다.**

### 전공 경험 🔍

  

- **개강 후 프로그래밍입문 수업을 따라가고 있습니다. 이 수업을 제외하고는 공부이력은 없습니다!**

### 기대되는 활동 또는 원하는 활동 📌

- **선배님들이랑 밤샘코딩에 참여해서 코딩에 대한 전문지식을 배우고 싶습니다. 그리고 무언가를 완성했을때의 뿌듯함을 느끼고 싶습니다!**

### 앞으로의 기대 ❗️

- **컴퓨터공학부 재학생답게 프로그래밍을 정복하고 싶습니다!**

**Comment by jang010505** [comment]
반갑습니다. OPG에 들어오신 것을 환영합니다. 저의 카카오 ID는 jang010505입니다. 여기로 카톡 한 번 주시면 바로 가입 시켜드리겠습니다.
