### ISSUE TITLE
OPG 가입신청입니다.!

### ISSUE THREAD

**Issue by LovelyMinji** [Openmind-Programming-Group/Introduction#8]
### 신청 계기 ❓

안녕하세요! 학과에서 OPG 홍보하는 글을 보고 관심이 생겨 신청하게 되었습니다. 컴퓨터공학부인만큼 프로그래밍 능력을 키우고 싶어 동아리에 들게 되었으며, 저는 혼자하는 공부보단 다 같이 공부했을때의 결과나 효율이 좋다고 생각합니다. 선배나 동기들과 함께 즐겁게 스터디하며 개발능력을 향상시키고 싶습니다.
동아리에서의 활동이 앞으로 너무너무 기대됩니다 !!

### 전공 경험 🔍

고등학교 때 생기부 활동으로 간단한 프로그래밍 제작하는데 있어 파이썬과 C#을 사용해본적 있지만 거의 찍먹,, 수준으로 막 잘 다룰 수 있는것은 아닙니다! 거의 신생아 수준! 그래도 목표를 이루기 위해 배워야 할 점이 있다면 열심히 노력하는 성격입니다.

### 기대되는 활동 또는 원하는 활동 📌

밤샘코딩! 경험해보고 싶습니다. 세미나, 작품전시회도 다 해보고 싶습니다!!

### 앞으로의 기대 ❗️

모르는게 없는 프로그래밍 신이 되고 싶습니다. 저는 모르는것을 새로 배워나가는 것도 좋아하지만 누군가에게 가르쳐주는 것 또한 좋아합니다. 따라서 1, 2 학년땐 동기나 선배들 아래서 열심히 배우고 싶고 고학년이 된다면 새로 들어오는 친구들에게 제가 배웠던 많은 것을 알려주고 싶습니다.

감사합니다.

**Comment by jang010505** [comment]
반갑습니다. OPG에 들어오신 것을 환영합니다. 저의 카카오 ID는 jang010505입니다. 여기로 카톡 한 번 주시면 바로 가입 시켜드리겠습니다.
