### ISSUE TITLE
OPG 가입신청

### ISSUE THREAD

**Issue by Min-Wooo** [Openmind-Programming-Group/Introduction#9]
### 신청 계기 ❓

- 카톡방 홍보로 알게 되었습니다. 부원분들과 같이 코딩에 대해 알아가면서 더 발전하고 싶었고, '밤샘코딩' 이라는 활동이 대학교에 오기 전에도 한 번쯤 해보고 싶었는데 마침 존재하는 활동이여서 지원하게 되었습니다.

### 전공 경험 🔍

  

- 고등학교 때 인천대 대학연계 프로그램 참여해 microbit랑 센서로 간단하게 프로그램 배웠습니다.

### 기대되는 활동 또는 원하는 활동 📌

- 밤샘코딩 해보고싶습니다ㅎㅎㅎ

### 앞으로의 기대 ❗️

- 대학교를 졸업할 때 OPG 활동이 제 발전의 한 축이 되었다고 말할 수 있도록 선배님들의 가르침도 잘 받고, 저 스스로도 공부하며 '저만의 프로그램'을 당당히 개발할 수 있도록 하겠습니다!! 뽑아주세요!

**Comment by jang010505** [comment]
반갑습니다. OPG에 들어오신 것을 환영합니다. 저의 카카오 ID는 jang010505입니다. 여기로 카톡 한 번 주시면 바로 가입 시켜드리겠습니다.
